version: '2'

services:
  api:
    build: ./api
    volumes:
      - ~/.aws:/root/.aws
      - ./api:/api
    ports:
      - "5000:5000"
    env_file:
      - web-variables.env
    environment:
      AWS_DEFAULT_REGION: us-west-2
  web:
    build: ./web
    volumes:
      - ~/.aws:/root/.aws
      - ./web:/web
    depends_on:
      - api
    links:
      - api
    ports:
      - "3000:3000"
    env_file:
      - web-variables.env
    environment:
      AWS_DEFAULT_REGION: us-west-2