version: '2'

services:
  api:
    build: ./api
    volumes:
      - ~/.aws:/root/.aws
      - ./api:/api
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    command: python -m flask run --host=0.0.0.0
  web:
    build: ./web
    volumes:
      - ~/.aws:/root/.aws
      - ./web:/web
      - node_modules:/web/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_RESOURCE_MESSAGES_URL=http://localhost:5000/api/messages
      - REACT_APP_OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - REACT_APP_OKTA_CLIENT_SECRET=${OKTA_CLIENT_SECRET}
      - REACT_APP_OKTA_ISSUER=${OKTA_ISSUER}
      - REACT_APP_OKTA_REDIRECT_URI=${OKTA_REDIRECT_URI}
      - REACT_APP_OKTA_SCOPE=${OKTA_SCOPE}
    depends_on:
      - api


volumes:
  node_modules: